# Source: jxboot-helmfile-resources/templates/upgrade-cj.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-boot-upgrade
  labels:
    app: jenkins-x-upgrade-processor
    release: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: jenkins-x-upgrade-processor
            release: jx
        spec:
          containers:
            - args:
                - boot
                - upgrade
                - --git-credentials
                - --batch-mode
              command:
                - jxl
              env:
                - name: HOME
                  value: /home
              image: gcr.io/jenkinsxio-labs-private/jxl:0.0.130
              imagePullPolicy: Always
              name: jenkins-x-upgrade-processor
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  successfulJobsHistoryLimit: 3
  schedule: "0 * * * *"
  suspend: false
