# Source: resources/templates/tekton-clusterrole.yaml
# Source: resources/templates/tekton-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-tekton-pipelines
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
      - create
      - update
