filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
- name: dev2
  url: http://chartmuseum-jx.34.89.8.12.nip.io/
releases:
- chart: dev/nodey560
  version: 0.0.18
  name: nodey560
  values:
  - jx-values.yaml
- chart: dev2/nodey546
  version: 1.0.33
  name: nodey546
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
