apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  jenkins-tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-tekton-pipelines
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: myjenkinsc
