apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-tekton-pipelines
rules:
  - apiGroups:
    - tekton.dev
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
    - create
    - update
  - apiGroups:
      - ""
    resources:
    - pods
    - pods/log
    verbs:
    - list
    - get
