apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipelines
rules:
  - apiGroups:
    - tekton.dev
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
    - create
    - update
