# Source: nodey546/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-23T17:29:56Z"
  deletionTimestamp: null
  name: 'nodey546-1.0.29'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.29
      sha: 93262f440eb1c66d6b1f25ed3bec68da2dcb19c5
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: c8c179d2958ed4beb4a82986390d840d29e0152b
  gitHttpUrl: https://github.com/jstrachan/nodey546
  gitOwner: jstrachan
  gitRepository: nodey546
  name: 'nodey546'
  releaseNotesURL: https://github.com/jstrachan/nodey546/releases/tag/v1.0.29
  version: v1.0.29
status: {}
