# Source: jxboot-helmfile-resources/templates/build-bot-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tekton-bot"
  annotations:
    iam.gke.io/gcp-service-account: jstrachan-tekton3-tekton@jenkins-x-labs-bdd1.iam.gserviceaccount.com
  namespace: myjenkinsa
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
secrets:
  - name: tekton-container-registry-auth
  - name: tekton-git
